CXXFLAGS = \
  -std=c++14 \
  -Wall \
  -Wextra \
  -Wconversion \
  -Wsign-conversion \
  -O2 \
  -isystem ../include

PRODUCTS = \
  abc \
  feedback_cycle


.PHONY: all clean

all: $(PRODUCTS)
	@:

clean:
	rm -f $(PRODUCTS)
